### PR TITLE
remove fastentrypoints & simplify code without it

### PR DESCRIPTION
**Pull request by igalic**
we can do without it, so lets.

### CODE REVIEW

**Comment by skarekrow** [comment]
Why? It speeds up execution.

**Comment by igalic** [comment]
because it's an optimization we don't need or use
(according to the helpful people in #python. and as such, pointless)

**Comment by skarekrow** [comment]
https://github.com/iocage/iocage/issues/72 this was the original issue, and it was certainly useful then. I can't imagine what changed the situation.

**Comment by igalic** [comment]
i love how this whole PR is a perfect example for [Chsterton's Fence](https://en.wikipedia.org/wiki/Wikipedia:Chesterton%27s_fence)

**Comment by ninjaaron** [comment]
lol

**Pull request merged**
